const GithubIDActionTypes = {
  GITHUBID_USERS_REQUEST: 'GITHUBID_USERS_REQUEST',
  GITHUBID_USERS_INPUT_SEARCH_KEY: 'GITHUBID_USERS_INPUT_SEARCH_KEY',
  GITHUBID_USER_DOES_NOT_EXIST: 'GITHUBID_USER_DOES_NOT_EXIST',
  GITHUBID_USER_EXISTS: 'GITHUBID_USER_EXISTS',
  GITHUBID_STORE_USER: 'GITHUBID_STORE_USER',
  NEW_GITHUB_ID_ENTRY: 'NEW_GITHUB_ID_ENTRY',
};

export default GithubIDActionTypes;
