const GithubIDActionTypes = {
  GITHUB_USERS_REQUEST: 'GITHUB_USERS_REQUEST',
  GITHUB_USERS_INPUT: 'GITHUB_USERS_INPUT',
  GITHUB_USER_DOES_NOT_EXIST: 'GITHUB_USER_DOES_NOT_EXIST',
  GITHUB_USER_EXISTS: 'GITHUB_USER_EXISTS',
  GITHUB_USER_STORE_USER: 'GITHUB_USER_STORE_USER',
  NEW_GITHUB_ID_ENTRY: 'NEW_GITHUB_ID_ENTRY',
};

export default GithubIDActionTypes;
