const GithubIDActionTypes = {
  GITHUB_USERS_REQUEST: 'GITHUB_USERS_REQUEST',
  GITHUB_USERS_INPUT: 'GITHUB_USERS_INPUT',
  GITHUB_USER_DOES_NOT_EXIST: 'GITHUB_USER_DOES_NOT_EXIST',
  GITHUB_USER_EXIST: 'GITHUB_USER_EXIST',
  GITHUB_USER_RESPONSE: 'GITHUB_USER_RESPONSE',
};

export default GithubIDActionTypes;
