# 1st stage to build the image
FROM node:20-alpine as builder

WORKDIR /app

COPY /emails /emails
COPY /.react-email /.react-email
RUN npm install

# RUN mkdir /.npm
# RUN chgrp -R 0 /.npm && \
#     chmod -R g=u /.npm

EXPOSE 3001
CMD ["npm", "run", "dev"]
