packages:
- app
- data-migrations
- sandbox/_packages/keycloak-admin
- sandbox/keycloak-provision
- sandbox/m365mock
- sandbox/nats-provision

overrides:
  conventional-changelog-conventionalcommits: ^10.0.0
  eslint-plugin-react-hooks: ^7.0.0

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  canvas: true
  core-js-pure: true
  prisma: true
  sharp: true
  unrs-resolver: true
  cypress: true
  esbuild: true
