packages:
- app
- data-migrations
- sandbox/_packages/keycloak-admin
- sandbox/keycloak-provision
- sandbox/m365mock
- sandbox/nats-provision

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  canvas: true
  core-js-pure: true
  cypress: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
