FROM node:22.12.0-alpine3.19

WORKDIR /app

RUN apk add --no-cache jq

COPY package.json ./package.json.tmp
COPY prisma/schema.prisma .

RUN npm install prisma@$(jq -r '.devDependencies.prisma' package.json.tmp)

CMD ["node_modules/.bin/prisma", "db", "push", "--schema", "schema.prisma", "--skip-generate"]
