export enum GlobalRole {
  ServiceAccount = 'service-account',
  User = 'user',
  Admin = 'admin',
  Editor = 'editor',
  Reader = 'reader',
  Analyzer = 'analyzer',
  PrivateAdmin = 'private-admin',
  PrivateAnalyzer = 'private-analyzer',
  PrivateEditor = 'private-editor',
  PrivateReader = 'private-reader',
  PublicAdmin = 'public-admin',
  PublicAnalyzer = 'public-analyzer',
  PublicEditor = 'public-editor',
  PublicReader = 'public-reader',
  Approver = 'approver',
  BillingReviewer = 'billing-reviewer',
  Billingreader = 'billing-reader',
}

export const RoleToSessionProp = {
  [GlobalRole.ServiceAccount]: 'isServiceAccount',
  [GlobalRole.User]: 'isUser',
  [GlobalRole.Admin]: 'isAdmin',
  [GlobalRole.Editor]: 'isEditor',
  [GlobalRole.Reader]: 'isReader',
  [GlobalRole.Analyzer]: 'isAnalyzer',
  [GlobalRole.PrivateAdmin]: 'isPrivateAdmin',
  [GlobalRole.PrivateAnalyzer]: 'isPrivateAnalyzer',
  [GlobalRole.PrivateEditor]: 'isPrivateEditor',
  [GlobalRole.PrivateReader]: 'isPrivateReader',
  [GlobalRole.PublicAdmin]: 'isPublicAdmin',
  [GlobalRole.PublicAnalyzer]: 'isPublicAnalyzer',
  [GlobalRole.PublicEditor]: 'isPublicEditor',
  [GlobalRole.PublicReader]: 'isPublicReader',
  [GlobalRole.Approver]: 'isApprover',
  [GlobalRole.BillingReviewer]: 'isBillingReviewer',
  [GlobalRole.Billingreader]: 'isBillingReader',
};

export const sessionRolePropKeys = Object.values(RoleToSessionProp);
