name: MS Teams Notification
description: Send a notification to MS Teams using a webhook URL and a custom message.

inputs:
  webhook-url:
    description: The MS Teams webhook URL
    required: true
  data:
    description: The JSON payload to send to MS Teams
    required: true

runs:
  using: composite
  steps:
  - run: |
      curl -X POST -H "Content-Type: application/json" -d '${{ inputs.data }}' '${{ inputs.webhook-url }}'
    shell: bash
