Feature: Edit Request

  Scenario: Create Private Cloud Edit Request and check visibility
    Given User logs in with username "james.smith@gov.bc.ca" and password "james.smith@gov.bc.ca"
    When User clicks tab "PRIVATE CLOUD OPENSHIFT"
    And User clicks button "Request a new product"
    And User types "Automated Test Product Name Compare Data" in "Product name"
    And User types "Automated Test to compare data Description" in "Description"
    And User selects "Citizens Services" in "Ministry"
    And User clicks and selects "SILVER" in "Hosting tier"
    And User clicks tab "Team members"
    And User chooses to edit contact "Project Owner"
    And User types and selects email "james.smith@gov.bc.ca"
    And User chooses to edit contact "Primary Technical Lead"
    And User types and selects email "john.doe@gov.bc.ca"
    And User makes a screenshot
    And User clicks button "Submit"
    And User checks checkbox "By checking this box..."
    And User clicks modal window button "Submit"
    And User clicks modal window button "Close"
    Then User should be redirected to Requests tab
    And User should see "Automated Test Product Name"
    And User logs out
    And User logs in with username "private.reviewer.system@gov.bc.ca" and password "private.reviewer.system@gov.bc.ca"
    And User clicks tab "PRIVATE CLOUD OPENSHIFT"
    And User waits for "3" seconds
    And User clicks tab "Requests"
    And User waits for "3" seconds
    And User clicks link "Automated Test Product Name Compare Data"
    And User clicks button "Approve"
    And User clicks modal window button "Submit"
    And User clicks modal window button "Return to Dashboard"
    And User logs out
    And User logs in with username "james.smith@gov.bc.ca" and password "james.smith@gov.bc.ca"
    And User clicks tab "PRIVATE CLOUD OPENSHIFT"
    When User clicks link "Automated Test Product Name Compare Data"
    And User waits for "3" seconds
    And User types "Automated Test Edit Request Compare Data" in "Product name"
    And User types "Automated Test to compare data Description Edit" in "Description"
    And User selects "Finance" in "Ministry"
    And User clicks tab "Team members"
    And User chooses to edit contact "Project Owner"
    And User types and selects email "jenna.anderson@gov.bc.ca"
    And User chooses to edit contact "Primary Technical Lead"
    And User types and selects email "sarah.williams@gov.bc.ca"
    And User chooses to edit contact "Secondary Technical Lead"
    And User types and selects email "kevin.taylor@gov.bc.ca"
    And User types "12345678901" in "After-Hours support contact"
    And User clicks tab "Additional team members"
    And User clicks button "Add New"
    And User chooses to edit additional team member
    And User types and selects email "jessica.davis@gov.bc.ca"
    And User clicks tab "Quotas"
    And User types quota "1" in "CPU" for "Development"
    And User types quota "3" in "MEMORY" for "Development"
    And User types quota "2" in "STORAGE" for "Development"
    And User types quota "1" in "CPU" for "Test"
    And User types quota "3" in "MEMORY" for "Test"
    And User types quota "2" in "STORAGE" for "Test"
    And User types quota "1" in "CPU" for "Production"
    And User types quota "3" in "MEMORY" for "Production"
    And User types quota "2" in "STORAGE" for "Production"
    And User types quota "1" in "CPU" for "Tools"
    And User types quota "3" in "MEMORY" for "Tools"
    And User types quota "2" in "STORAGE" for "Tools"
    And User types justification "John Cypress" in "Contact name"
    And User types justification "testemail@artemtest.com" in "Contact email"
    And User types justification "Test Justification text, test-test, 123" in "Justification of quota increase"
    And User clicks tab "Webhooks"
    And User types "https://test-artem.test-artem.artem" in "URL"
    And User types "123test456secret789" in "Secret"
    And User types "artem.test" in "Username"
    And User types "test-test" in "Password"
    And User clicks button "Submit"
    And User clicks modal window button "Submit"
    And User clicks modal window button "Close"
    And User waits for "2" seconds
    Then User should be redirected to Requests tab
    And User should see "Automated Test Edit Request Compare Data"
    And User logs out
    And User logs in with username "private.reviewer.system@gov.bc.ca" and password "private.reviewer.system@gov.bc.ca"
    And User clicks tab "PRIVATE CLOUD OPENSHIFT"
    And User waits for "3" seconds
    And User clicks tab "Requests"
    And User waits for "3" seconds
    And User clicks link "Automated Test Edit Request Compare Data"
    And User clicks button "Approve"
    And User clicks modal window button "Submit"
    And User clicks modal window button "Return to Dashboard"
    And User clicks tab "Products"
    Then User should see "Automated Test Edit Request Compare Data"
    And User logs out
    And User logs in with username "jenna.anderson@gov.bc.ca" and password "jenna.anderson@gov.bc.ca"
    And User clicks tab "PRIVATE CLOUD OPENSHIFT"
    And User clicks link "Automated Test Edit Request Compare Data"
    And User waits for "2" seconds
    Then User sees "Automated Test Edit Request Compare Data" in "Product name"
    And User sees "Automated Test to compare data Description Edit" in "Description"
    And User sees "SILVER" in "Hosting tier"
    And User clicks tab "Team members"
    And User checks "Project Owner" is set to "jenna.anderson@gov.bc.ca"
    And User checks "Primary Technical Lead" is set to "sarah.williams@gov.bc.ca"
    And User checks "Secondary Technical Lead" is set to "kevin.taylor@gov.bc.ca"
    And User sees "+1 (234) 567-8901" in "After-Hours support contact"
    And User clicks tab "Additional team members"
    And User confirms Additional team members is set to "jessica.davis@gov.bc.ca"
    And User clicks tab "Quotas"
    And User verifies quota value is "1" in "CPU" for "Development"
    And User verifies quota value is "3" in "MEMORY" for "Development"
    And User verifies quota value is "2" in "STORAGE" for "Development"
    And User verifies quota value is "1" in "CPU" for "Test"
    And User verifies quota value is "3" in "MEMORY" for "Test"
    And User verifies quota value is "2" in "STORAGE" for "Test"
    And User verifies quota value is "1" in "CPU" for "Production"
    And User verifies quota value is "3" in "MEMORY" for "Production"
    And User verifies quota value is "2" in "STORAGE" for "Production"
    And User verifies quota value is "1" in "CPU" for "Tools"
    And User verifies quota value is "3" in "MEMORY" for "Tools"
    And User verifies quota value is "2" in "STORAGE" for "Tools"
