Feature: New Request

  Scenario: Create Public Cloud Request and check visibility
    Given User logs in with username "james.smith@gov.bc.ca" and password "james.smith@gov.bc.ca"
    When User clicks tab "PUBLIC CLOUD LANDING ZONES"
    And User clicks button "REQUEST A NEW PRODUCT"
    And User types "Automated Test Product Public" in "Product Name"
    And User types "Automated Test Description" in "Description"
    And User selects "Citizens Services" in "Ministry"
    And User selects "AWS" in "Cloud Service Provider"
    And User clicks button "Select None"
    And User checks checkbox "Test Account"
    And User checks checkbox "Tools Account"
    And User types and selects "james.smith@gov.bc.ca" in "Product Owner Email"
    And User types and selects "john.doe@gov.bc.ca" in "Technical Lead Email"
    And User types and selects "public.admin.system@gov.bc.ca" in "Expense Authority Email"
    And User types "77.33" in "Estimated average monthly spend - Test..."
    And User types "111.22" in "Estimated average monthly spend - Tool..."
    And User types "123" in "Client Code"
    And User types "4A5B6" in "Responsibility Centre (RC)"
    And User types "78901" in "Service Line (SL)"
    And User types "2345" in "Standard Object of Expense (STOB)"
    And User types "6789012" in "Project Code"
    And User clicks button "SUBMIT REQUEST"
    And User checks checkbox "...has signed a Memorandum of Understanding..."
    And User checks checkbox "...is liable to pay the base charge..."
    And User clicks modal window button "SUBMIT REQUEST"
    And User clicks button "Return to Dashboard"
    Then User should be redirected to Requests tab
    And User should see Request with name "Automated Test Product Public"
