name: Trivy Scan Action
description: Scan Docker images using Trivy and upload results.
inputs:
  image:
    description: A docker image
    required: true

runs:
  using: composite
  steps:
  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@1bd062560b422f5944df1de50abd05162bea079e
    continue-on-error: true
    with:
      image-ref: ${{ inputs.image }}
      format: sarif
      output: trivy-results.sarif
      vuln-type: os,library
      severity: LOW,MEDIUM,HIGH,CRITICAL

  - name: Upload Trivy scan results to GitHub Security tab
    uses: github/codeql-action/upload-sarif@16adc4e6724ac45e5514b2814142af61054bcd2a
    continue-on-error: true
    with:
      sarif_file: trivy-results.sarif
      category: ${{ inputs.image }}
