BEGIN TRANSACTION;

ALTER TABLE profile 
ADD COLUMN IF NOT EXISTS notification_email BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS notification_sms BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS notification_ms_teams BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS payment_bambora BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS payment_pay_bc BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS file_transfer BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS file_storage BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS geo_mapping_web BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS geo_mapping_location BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS scheduling_calendar BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS scheduling_appointments BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS identity_management_site_minder BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS identity_management_keycloak BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS identity_management_active_dir BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS other varchar(512);

END TRANSACTION;
