BEGIN TRANSACTION;

ALTER TABLE profile 
ADD COLUMN IF NOT EXISTS notificationEmail BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS notificationSMS BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS notificationMSTeams BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS paymentBambora BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS paymentPayBC BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS fileTransfer BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS fileStorage BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS geoMappingWeb BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS geoMappingLocation BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS schedulingCalendar BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS schedulingAppointments BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS identityManagementSiteMinder BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS identityManagementKeyCloak BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS identityManagementActiveDir BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS other varchar(512);

END TRANSACTION;