BEGIN TRANSACTION;

ALTER TABLE cluster_namespace 
ADD COLUMN IF NOT EXISTS quota_cpu VARCHAR(8),
ADD COLUMN IF NOT EXISTS quota_memory VARCHAR(8),
ADD COLUMN IF NOT EXISTS quota_storage VARCHAR(8);

END TRANSACTION;
