BEGIN TRANSACTION;

ALTER TABLE profile 
ADD COLUMN IF NOT EXISTS pvc_deletability BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS namespace_deletability BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS pods_deletability BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS provisoner_deletion_checked BOOLEAN NOT NULL DEFAULT false;

END TRANSACTION;
