name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@b61f648b0dc314e25fc81ac7d4e32a24a5ab5486 # v0.27.1
    with:
      plugins: |
        sonarscanner=https://github.com/virtualstaticvoid/asdf-sonarscanner.git
        database-tools=https://github.com/egose/asdf-database-tools.git

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
