name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Temporarily exclude pnpm from asdf
    run: |
      cp .tool-versions .tool-versions.ci
      grep -v '^pnpm ' .tool-versions > .tool-versions.tmp
      mv .tool-versions.tmp .tool-versions
    shell: bash

  - name: Setup Tools
    uses: egose/actions/asdf-tools@2cddbcad7377a3b715a1f0bd3c5f0e4d448b2110 # v0.32.2
    with:
      plugins: |
        sonarscanner=https://github.com/virtualstaticvoid/asdf-sonarscanner.git
        database-tools=https://github.com/egose/asdf-database-tools.git

  - name: Restore tool versions
    run: mv .tool-versions.ci .tool-versions
    shell: bash

  - name: Setup pnpm
    uses: pnpm/setup@v2
    with:
      install: false

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
