name: Setup Tools
description: Setup required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup Tools
    uses: egose/actions/asdf-tools@e15b9c2e3b42cc9ca49641cf6a428f7c7e503ae5 # v0.19.0
    with:
      plugins: |
        sonarscanner=https://github.com/virtualstaticvoid/asdf-sonarscanner.git
        database-tools=https://github.com/egose/asdf-database-tools.git

  - name: Install python tools
    run: |
      pip install -r requirements.txt
      asdf reshim
    shell: bash
